FROM localhost/freebsd-base:14.3-beta3
MAINTAINER Bretton Vine <bv@honeyguide.eu>

RUN host pkg.freebsd.org

RUN ping -4 -c 3 pkg.freebsd.org

RUN ping6 -c 3 pkg.freebsd.org

# Set entrypoint
ADD entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT "/usr/local/bin/entrypoint.sh"
