FROM docker.io/freebsd/freebsd-runtime:14.3-beta4
MAINTAINER Bretton Vine <bv@honeyguide.eu>

RUN cat /etc/resolv.conf

RUN ping -4 -c 3 pkg.freebsd.org

RUN ping6 -c 3 pkg.freebsd.org

RUN route get pkg.freebsd.org

RUN fetch -4 http://ipv4.download.thinkbroadband.com/5MB.zip -o ipv4.zip

RUN fetch -6 http://ipv6.download.thinkbroadband.com/5MB.zip -o ipv6.zip

RUN ASSUME_ALWAYS_YES=yes pkg bootstrap -f

# Set entrypoint
ADD entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT "/usr/local/bin/entrypoint.sh"
